# AUTEUR : LDM
# CREATION : 30.04.2026
# contains board logic and data

# MISSING : MANAGEMENT OF A SINGLE PLAYER'S GIRD | CURRENTLY SELECTED CASE | CASE STATES (ALL OF THEM) | SHIP PLACEMENTS | SHIPS LEFT | COLLISIONS