# AUTEUR : LDM
# CREATION : 30.04.2026
# Contain the constants used about everywhere else in the code

from enum import Enum

# Colors

BLUE = (0,148,255)
DARK_BLUE = (0,38,255)
LIGHT_GRAY = (226,222,222)
GRAY = (128,128,128)
DARK_GRAY = (64,64,64)
YELLOW = (255,216,0)
RED = (255,0,0)
BLACK = (0,0,0)
WHITE = (255,255,255)

# UI specific constants

SCREEN_WIDTH = 1024 # game windows' width
SCREEN_HEIGHT = 768 # game windows' height
CASE_DIMENSION = 40 # width and height of each case in grids
OUTLINE_THICKNESS = 5 # ships' and selected case outline

#TODO HERE: ADD USUAL TEXT FONT AND SIZE (AND THE IA LOG VARIANT IF IT IS NEEDED)

BACKGROUND_COLOR = GRAY

OCEAN_COLOR_PRIMARY = BLUE
OCEAN_COLOR_SECONDARY = DARK_BLUE

TEXT_COLOR = LIGHT_GRAY

BOAT_OUTLINE_COLOR = LIGHT_GRAY
BOAT_INSIDE_COLOR = GRAY

SINKED_BOAT_OUTLINE_COLOR = GRAY
SINKED_BOAT_INSIDE_COLOR = DARK_GRAY

ICON_COLOR = LIGHT_GRAY

SELECTED_COLOR = YELLOW
MISS_COLOR = WHITE
HIT_COLOR = RED
SINKED_COLOR = BLACK

# multi-domain constants

GRID_SIZE = 10
SHIP_PER_PLAYER = 5
IA_LOG_LINE_LIMIT = 20
IA_LOG_CHARACTER_PER_LINE_LIMIT = 50

class ORIENTATION(Enum):
    HORIZONTAL = False
    VERTICAL = True

class CASE_STATE(Enum):
    CLEAN = 0
    MISS = 1
    HIT = 1
    SUNK = 2

#TODO HERE: SHIP NAMES AND SIZES