# AUTEUR : LDM
# CREATION : 30.04.2026
# contain the logic related to the gameplay

# MISSING : TURN NUMBER | GAMEMODE (AND CURRENT GAME MODE) | PLAY ORDER (AND TRACKING OF THAT) | SHOTS LEFT | BOTH PARTICIPANT'S BOARD